<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LAWN</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <StartupObject>Program</StartupObject>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <RootNamespace></RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Platforms\**\*.cs" />
    <EmbeddedResource Include="Lawn.Strings.resx" />
    <None Include="Microsoft.Xna.Framework.RuntimeProfile" />
    <None Include="Microsoft.Xna.Framework.XlastConfiguration" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Content\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="resources.xml;todresources.xml;LawnStrings_*.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
